fix: add explicit return types
The return type of `NumericFormat` and `PatternFormat` was being inferred as
`JSX.Element` which caused the following type error (typescript v5.7.3):

```
error TS2786: 'PatternFormat' cannot be used as a JSX component.
  Its type '<BaseType = InputAttributes>(props: PatternFormatProps<BaseType>) => Element' is not a valid JSX element type.
    Type '<BaseType = InputAttributes>(props: PatternFormatProps<BaseType>) => Element' is not assignable to type '(props: any) => ReactNode | Promise<ReactNode>'.
      Type 'Element' is not assignable to type 'ReactNode | Promise<ReactNode>'.
        Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.
```

Instead of being inferred, explicitly add the return type of `React.ReactElement`
which represents a JSX element.